### ISSUE TITLE
It doens't work

### ISSUE THREAD

**Issue by PeterGottesman** [zraffo/nacs.us#1]
How does work

**Comment by PeterGottesman** [comment]
+1 I am having this issue too

**Comment by PeterGottesman** [comment]
@zraffo I am still having issues. Any help?

**Comment by zraffo** [comment]
uninstall and then reinstall

**Comment by PeterGottesman** [comment]
Thanks so much! I never would've thought of that. I really appreciate your help through this difficult journey.
it still doesnt work btw

**Comment by PeterGottesman** [comment]
I got it, thanks
